import { defineConfig, devices } from "@playwright/test";

const deploymentBasePath = "/BlissHack/";
const previewOrigin = "http://127.0.0.1:4176";
const basicFlowNames = [
  "uses n as the guarded Home New Game shortcut",
  "ignores n while the Home root is inert",
  "submits a non-empty character name on blur",
  "shows punctuation setup actions without intercepting name input",
  "uses comma as the unified Auto action during selection",
  "uses period as the unified Auto & Start action during selection",
  "keeps a available for the Archeologist accelerator",
  "keeps n available for the Neutral accelerator",
  "rejects guarded character accelerators:",
  "rejects guarded punctuation setup actions:",
  "activates a focused Role button with Space and advances focus",
  "cancels an existing-save name without restoring it",
  "uses the unified keyboard character setup flow",
  "renders default Tiles pixels and switches renderers without restarting",
  "plays through startup and routes terminal UI input",
  "enumerates a persisted save after returning home and refreshing",
  "exports, previews, imports, and restores a complete profile",
  "exports, clears, and restores a complete BlissHack backup",
  "exports, deletes, imports, and continues identical raw save bytes",
  "toggles extended-command description search without losing keyboard focus",
  "blocks a second game and retries after the owning page closes",
  "keeps a manual Follow anchor after a right-click position look",
  "right-drag pans during position input without submitting it",
  "delays status inspection and keeps pointer and focus tooltips in the shared viewport layer",
  "shows the core permanent-inventory item text without sending game input",
  "inspects the player cell without changing visible messages or turn count",
  "clears inspection tooltips on leave, game key input, and pause",
  "opens an anchored core map menu and cancels it without a turn",
  "restores the map trigger after every anchored-menu dismissal",
  "opens itemactions from permanent inventory without flashing its selector",
  "keeps permanent inventory mouse-only while core inventory accepts accelerators",
  "uses the global scrollbar palette across browser engines",
  "navigates result tabs by mouse and keyboard without moving Confirm",
  "confirms once with Enter from every endgame dialog focus target",
  "scrolls overflowing result tabs with a real vertical wheel",
  "keeps long sections independently scrollable without page overflow",
  "keeps Ranking in a focusable horizontal scroller at 320px",
  "fits the result shell at the supported minimum width",
  "moves real menu focus and restores the inventory trigger after Escape",
  "closes on left click outside and restores the inventory trigger",
  "prevents the native menu on right click outside and restores the inventory trigger",
  "uses two-column anchored actions without changing four-column menus",
  "uses a five-pixel threshold and rejects non-map drop targets",
  "highlights the player cell and cancels interrupted drags without commands",
  "drops one stack once and waits for a new permanent-inventory revision",
  "keeps worn items and shows the core drop rejection without a turn",
  "pauses only at command input and synchronizes in-game settings",
  "shows a fatal page and exports a private diagnostic log",
  "shows a recoverable module fatal page when the loader returns 404",
  "releases the game lock after fatal session cleanup",
  "does not overwrite a profile changed by another idle page",
  "collects a real unified-character quit into the BlissHack summary",
  "BlissHack keeps getdir map clicks on adjacent cells without moving the dock",
  "BlissHack passes getdir help to the core and retries direction input",
  "getdir buttons preserve Tab and native keyboard activation",
  "action item selection still advances into the shared direction overlay",
  "ynq focuses its default and accepts direct q",
  "Escape selects Quit from a real ynq prompt",
  "focused Yes submits a default-No yn prompt",
  "BlissHack yn buttons preserve keyboard and Escape semantics outside the dock",
  "Messages invokes the real prevmsg action and opens the larger history dialog",
  "compact PICK_ONE cancel keeps native keyboard activation",
  "Action bar integration:",
  "Action bar layout transfer:",
  "HUD visual regression:",
].join("|");

export default defineConfig({
  testDir: "./test/integration-tests/browser",
  outputDir: "./test-results/playwright-compat",
  fullyParallel: false,
  workers: 1,
  forbidOnly: true,
  retries: 0,
  reporter: "list",
  grep: new RegExp(basicFlowNames),
  expect: {
    timeout: 15_000,
  },
  use: {
    baseURL: `${previewOrigin}${deploymentBasePath}`,
    headless: true,
    viewport: { width: 1280, height: 900 },
    screenshot: "only-on-failure",
    trace: "retain-on-failure",
  },
  projects: [
    {
      name: "firefox",
      use: { ...devices["Desktop Firefox"] },
    },
    {
      name: "webkit",
      use: { ...devices["Desktop Safari"] },
    },
  ],
  webServer: {
    command: `VITE_E2E_FIXTURES=1 VITE_BASE_PATH=${deploymentBasePath} npm run build && VITE_BASE_PATH=${deploymentBasePath} npm run preview -- --host 127.0.0.1 --port 4176 --strictPort`,
    url: `${previewOrigin}${deploymentBasePath}`,
    reuseExistingServer: !process.env.CI,
    timeout: 120_000,
  },
});
