import {
  NHW_MAP,
  NHW_MENU,
  NHW_MESSAGE,
  NHW_STATUS,
  NHW_TEXT,
  PICK_NONE,
  PICK_ONE,
  type MenuItem,
  type TextLine,
  type WindowState,
} from "../game-state";

/** Presentation mode selected for one session's endgame flow. */
export type EndgameStyle = "original" | "blisshack";

/** Module and session identities which own one collector. */
export interface EndgameCollectorOwner {
  moduleId: string;
  sessionId: string;
}

/** Observable collection phases used by lifecycle tests and diagnostics. */
export type EndgameCollectorPhase =
  | "idle"
  | "collecting-disclosure"
  | "collecting-summary"
  | "collecting-ranking"
  | "complete"
  | "fallback";

/** Reasons which invalidate an unfinished collection. */
export type EndgameCollectorResetReason =
  | "bridge-reset"
  | "fatal"
  | "session-replaced";

/** Window data copied from mutable game state at a display boundary. */
export interface EndgameWindowSnapshot {
  id: number;
  type: number;
  lines: readonly TextLine[];
  menuItems: readonly MenuItem[];
  menuPrompt: string;
}

/** One immutable text or menu block generated by the core. */
export type EndgameContentBlock =
  | {
    kind: "text";
    sourceWindowId: number | null;
    lines: readonly TextLine[];
  }
  | {
    kind: "menu";
    sourceWindowId: number;
    lines: readonly TextLine[];
    prompt: string;
    items: readonly MenuItem[];
  };

/** One displayed tab in the completed endgame result. */
export interface EndgameSection {
  kind: "summary" | "disclosure" | "ranking";
  title: string;
  blocks: readonly EndgameContentBlock[];
}

/** Self-contained result which remains valid after its WASM module retires. */
export interface EndgameSummary {
  owner: EndgameCollectorOwner;
  sections: readonly EndgameSection[];
}

/** Whether the bridge should continue normally or resolve one callback. */
export type EndgameCollectorDecision =
  | { kind: "pass" }
  | { kind: "resolve"; value?: number };

/** Bridge event types relevant to endgame collection. */
export type EndgameCollectorEvent =
  | {
    type: "yn";
    query: string;
    choices: string | null;
    defaultCode: number;
  }
  | {
    type: "window-created";
    windowId: number;
    windowType: number;
  }
  | {
    type: "window-destroyed";
    windowId: number;
  }
  | {
    type: "display-window";
    window: EndgameWindowSnapshot;
    blocking: boolean;
  }
  | {
    type: "select-menu";
    window: EndgameWindowSnapshot;
    how: number;
  }
  | {
    type: "raw-print";
    line: TextLine;
  }
  | {
    type: "input-request";
    inputKind: string;
  };

/** Read-only collector state exposed for lifecycle coordination and tests. */
export interface EndgameCollectorState {
  phase: EndgameCollectorPhase;
  owner: EndgameCollectorOwner | null;
  currentDisclosureTitle: string | null;
  fallbackReason: string | null;
  summary: EndgameSummary | null;
}

/** Pure state machine which consumes copied shim events. */
export interface EndgameCollector {
  handle(event: EndgameCollectorEvent): EndgameCollectorDecision;
  getState(): Readonly<EndgameCollectorState>;
  complete(): EndgameSummary | null;
  setStyle(style: EndgameStyle): void;
  reset(reason: EndgameCollectorResetReason): void;
}

/** Session-scoped inputs required by the collector. */
export interface EndgameCollectorOptions {
  owner: EndgameCollectorOwner;
  style: EndgameStyle;
  isGameOver(): boolean;
}

interface MutableSection {
  kind: EndgameSection["kind"];
  title: string;
  blocks: EndgameContentBlock[];
}

const PASS: EndgameCollectorDecision = Object.freeze({ kind: "pass" });
const RESOLVE_DISPLAY: EndgameCollectorDecision = Object.freeze({
  kind: "resolve",
});
const RESOLVE_MENU: EndgameCollectorDecision = Object.freeze({
  kind: "resolve",
  value: 0,
});
const RESOLVE_YES: EndgameCollectorDecision = Object.freeze({
  kind: "resolve",
  value: "y".charCodeAt(0),
});
const DISCLOSURE_CHOICES = new Set(["ynq", "ynaq", "ynq\u001ba"]);
const INVENTORY_DISCLOSURE_QUERY =
  /^Do you want (?:your possessions identified|to see what you had when you (?:quit|died))\?$/;
let activeCollector: EndgameCollector | null = null;

/**
 * Create one session-scoped endgame event collector.
 * @param options - immutable owner, style, and authoritative game-over reader.
 * @returns a pure collector with no React or WASM calls.
 */
export function createEndgameCollector(
  options: EndgameCollectorOptions,
): EndgameCollector {
  const configuredOwner = freezeOwner(options.owner);
  const hudWindows = new Map<number, number>();
  const destroyedHudWindows = new Set<number>();
  const summaryWindowIds = new Set<number>();
  const disclosures: MutableSection[] = [];
  const summaryBlocks: EndgameContentBlock[] = [];
  const rankingBlocks: EndgameContentBlock[] = [];
  let enabled = options.style === "blisshack";
  let phase: EndgameCollectorPhase = "idle";
  let currentDisclosure: MutableSection | null = null;
  let inventoryMenuPending = false;
  let fallbackReason: string | null = null;
  let completedSummary: EndgameSummary | null = null;

  /**
   * Consume one copied bridge event without invoking the core.
   * @param event - callback-derived event to inspect.
   * @returns whether the bridge should resolve the callback automatically.
   */
  function handle(event: EndgameCollectorEvent): EndgameCollectorDecision {
    if (phase === "fallback" || phase === "complete") return PASS;
    if (event.type === "window-created") {
      recordWindow(event.windowId, event.windowType);
      return PASS;
    }
    if (event.type === "window-destroyed") {
      recordWindowDestruction(event.windowId);
      return PASS;
    }
    if (!enabled) return PASS;
    if (!options.isGameOver()) return PASS;

    if (event.type === "yn") return handleYn(event);
    if (event.type === "display-window") return handleDisplay(event);
    if (event.type === "select-menu") return handleMenu(event);
    if (event.type === "raw-print") return handleRawPrint(event.line);
    return fallBack(`unexpected-${event.inputKind}`);
  }

  /**
   * Read a detached snapshot of the collector's current state.
   * @returns state suitable for assertions and lifecycle checks.
   */
  function getState(): Readonly<EndgameCollectorState> {
    return Object.freeze({
      phase,
      owner: enabled ? configuredOwner : null,
      currentDisclosureTitle: currentDisclosure?.title ?? null,
      fallbackReason,
      summary: completedSummary,
    });
  }

  /**
   * Freeze captured values once the owning core has completed.
   * @returns immutable summary, or null for disabled, incomplete, or fallback flows.
   */
  function complete(): EndgameSummary | null {
    if (!enabled || phase === "fallback" || phase === "idle") return null;
    if (completedSummary) return completedSummary;
    commitCurrentDisclosure();
    if (summaryBlocks.length === 0) {
      fallBack("missing-summary");
      return null;
    }

    const sections: EndgameSection[] = [
      {
        kind: "summary",
        title: "Summary",
        blocks: summaryBlocks,
      },
      ...disclosures,
    ];
    if (rankingBlocks.length > 0) {
      sections.push({
        kind: "ranking",
        title: "Ranking",
        blocks: rankingBlocks,
      });
    }
    completedSummary = freezeSummary({
      owner: configuredOwner,
      sections,
    });
    phase = "complete";
    return completedSummary;
  }

  /**
   * Apply the current session's live endgame presentation setting.
   * @param style - latest persisted style selected in game settings.
   */
  function setStyle(style: EndgameStyle): void {
    if (phase !== "idle") {
      if (style === "original" && enabled) fallBack("style-changed");
      return;
    }
    enabled = style === "blisshack";
  }

  /**
   * Invalidate all captured state after bridge or session cleanup.
   * @param _reason - lifecycle reason retained by the caller for diagnostics.
   */
  function reset(_reason: EndgameCollectorResetReason): void {
    enabled = false;
    phase = "idle";
    fallbackReason = null;
    completedSummary = null;
    currentDisclosure = null;
    inventoryMenuPending = false;
    disclosures.length = 0;
    summaryBlocks.length = 0;
    rankingBlocks.length = 0;
    hudWindows.clear();
    destroyedHudWindows.clear();
    summaryWindowIds.clear();
  }

  /** Track normal HUD identities before they are destroyed at game over. */
  function recordWindow(windowId: number, windowType: number): void {
    if (
      windowType === NHW_MESSAGE
      || windowType === NHW_STATUS
      || windowType === NHW_MAP
    ) {
      hudWindows.set(windowId, windowType);
    }
  }

  /** Advance from disclosure to summary, or summary to ranking, on destruction. */
  function recordWindowDestruction(windowId: number): void {
    if (hudWindows.has(windowId)) destroyedHudWindows.add(windowId);
    if (
      enabled
      &&
      options.isGameOver()
      && (phase === "idle" || phase === "collecting-disclosure")
      && hasDestroyedRequiredHud()
    ) {
      beginCollection();
      commitCurrentDisclosure();
      phase = "collecting-summary";
      return;
    }
    if (
      phase === "collecting-summary"
      && summaryWindowIds.has(windowId)
    ) {
      phase = "collecting-ranking";
    }
  }

  /** Auto-answer only the core's non-numeric disclosure choice contract. */
  function handleYn(
    event: Extract<EndgameCollectorEvent, { type: "yn" }>,
  ): EndgameCollectorDecision {
    beginCollection();
    if (
      phase !== "collecting-disclosure"
      || !event.choices
      || !DISCLOSURE_CHOICES.has(event.choices)
    ) {
      return fallBack("unexpected-yn");
    }
    commitCurrentDisclosure();
    currentDisclosure = {
      kind: "disclosure",
      title: disclosureTitle(event.query),
      blocks: [],
    };
    inventoryMenuPending = INVENTORY_DISCLOSURE_QUERY.test(event.query);
    return RESOLVE_YES;
  }

  /** Copy and acknowledge one blocking text window owned by endgame. */
  function handleDisplay(
    event: Extract<EndgameCollectorEvent, { type: "display-window" }>,
  ): EndgameCollectorDecision {
    beginCollection();
    if (!event.blocking) return PASS;
    captureWindow(event.window);
    return RESOLVE_DISPLAY;
  }

  /** Copy and acknowledge non-interactive menus plus the known inventory display. */
  function handleMenu(
    event: Extract<EndgameCollectorEvent, { type: "select-menu" }>,
  ): EndgameCollectorDecision {
    beginCollection();
    if (event.how === PICK_ONE) {
      if (
        phase !== "collecting-disclosure"
        || !inventoryMenuPending
        || !isInventoryDisclosureMenu(event.window)
      ) {
        return fallBack("unexpected-menu");
      }
      inventoryMenuPending = false;
    } else if (event.how !== PICK_NONE) {
      return fallBack("unexpected-menu");
    } else {
      inventoryMenuPending = false;
    }
    captureWindow(event.window);
    return RESOLVE_MENU;
  }

  /** Preserve raw score output after the summary window has closed. */
  function handleRawPrint(line: TextLine): EndgameCollectorDecision {
    beginCollection();
    if (phase !== "collecting-ranking") {
      return fallBack("unexpected-raw-output");
    }
    const lastBlock = rankingBlocks.at(-1);
    if (lastBlock?.kind === "text" && lastBlock.sourceWindowId === null) {
      rankingBlocks[rankingBlocks.length - 1] = {
        ...lastBlock,
        lines: [...lastBlock.lines, copyLine(line)],
      };
    } else {
      rankingBlocks.push({
        kind: "text",
        sourceWindowId: null,
        lines: [copyLine(line)],
      });
    }
    return PASS;
  }

  /** Enter disclosure collection on the first verified endgame event. */
  function beginCollection(): void {
    if (phase === "idle") phase = "collecting-disclosure";
  }

  /** Copy one displayed window into its current semantic section. */
  function captureWindow(window: EndgameWindowSnapshot): void {
    const block = blockFromWindow(window);
    if (!block) return;
    if (phase === "collecting-disclosure") {
      if (currentDisclosure) currentDisclosure.blocks.push(block);
      return;
    }
    if (phase === "collecting-summary") {
      summaryBlocks.push(block);
      summaryWindowIds.add(window.id);
      return;
    }
    if (phase === "collecting-ranking") rankingBlocks.push(block);
  }

  /** Keep a completed disclosure only when the core produced visible content. */
  function commitCurrentDisclosure(): void {
    if (currentDisclosure?.blocks.length) disclosures.push(currentDisclosure);
    currentDisclosure = null;
    inventoryMenuPending = false;
  }

  /** Stop automation while leaving the current core input untouched. */
  function fallBack(reason: string): EndgameCollectorDecision {
    phase = "fallback";
    fallbackReason = reason;
    completedSummary = null;
    currentDisclosure = null;
    inventoryMenuPending = false;
    disclosures.length = 0;
    summaryBlocks.length = 0;
    rankingBlocks.length = 0;
    return PASS;
  }

  /** Require map and message destruction plus any observed status window. */
  function hasDestroyedRequiredHud(): boolean {
    const requiredTypes = [NHW_MAP, NHW_MESSAGE];
    if ([...hudWindows.values()].includes(NHW_STATUS)) {
      requiredTypes.push(NHW_STATUS);
    }
    return requiredTypes.every((type) =>
      [...hudWindows].some(([id, trackedType]) =>
        trackedType === type && destroyedHudWindows.has(id)));
  }

  return { handle, getState, complete, setStyle, reset };
}

/**
 * Replace the process-wide collector for the sole active WASM session.
 * @param options - new session ownership and activation settings.
 */
export function setEndgameCollectorContext(
  options: EndgameCollectorOptions,
): void {
  activeCollector?.reset("session-replaced");
  activeCollector = createEndgameCollector(options);
}

/**
 * Route one bridge event to the active session collector.
 * @param event - copied callback event.
 * @returns whether the callback should continue or resolve immediately.
 */
export function handleEndgameCollectorEvent(
  event: EndgameCollectorEvent,
): EndgameCollectorDecision {
  return activeCollector?.handle(event) ?? PASS;
}

/**
 * Apply an in-game endgame-style change to the active session collector.
 * @param style - latest persisted style.
 */
export function updateEndgameCollectionStyle(style: EndgameStyle): void {
  activeCollector?.setStyle(style);
}

/**
 * Freeze the active collector after the core's main promise settles.
 * @returns detached result or null when collection was disabled or abandoned.
 */
export function completeEndgameCollection(): EndgameSummary | null {
  return activeCollector?.complete() ?? null;
}

/**
 * Inspect active collector state without retaining its mutable internals.
 * @returns current state or null when no session owns a collector.
 */
export function getEndgameCollectorState():
  Readonly<EndgameCollectorState> | null {
  return activeCollector?.getState() ?? null;
}

/**
 * Clear active collection when bridge or session ownership ends.
 * @param reason - lifecycle event which invalidated the collector.
 */
export function resetEndgameCollection(
  reason: EndgameCollectorResetReason,
): void {
  activeCollector?.reset(reason);
  activeCollector = null;
}

/**
 * Copy mutable game window data at the exact callback boundary.
 * @param window - live window state owned by game-state.
 * @returns detached collector snapshot.
 */
export function snapshotEndgameWindow(
  window: WindowState,
): EndgameWindowSnapshot {
  return {
    id: window.id,
    type: window.type,
    lines: window.lines.map(copyLine),
    menuItems: window.menuItems.map(copyMenuItem),
    menuPrompt: window.menuPrompt,
  };
}

/** Convert a copied NetHack window into one renderable result block. */
function blockFromWindow(
  window: EndgameWindowSnapshot,
): EndgameContentBlock | null {
  if (window.type === NHW_MENU) {
    if (
      window.lines.length === 0
      && !window.menuPrompt
      && window.menuItems.length === 0
    ) return null;
    return {
      kind: "menu",
      sourceWindowId: window.id,
      lines: window.lines.map(copyLine),
      prompt: window.menuPrompt,
      items: window.menuItems.map(copyMenuItem),
    };
  }
  if (window.type !== NHW_TEXT) return null;
  if (window.lines.length === 0) return null;
  return {
    kind: "text",
    sourceWindowId: window.id,
    lines: window.lines.map(copyLine),
  };
}

/**
 * Recognize the full-inventory menu produced by display_inventory(NULL, TRUE).
 * @param window - copied menu at its select boundary.
 * @returns whether the menu has the non-prompted selectable inventory shape.
 */
function isInventoryDisclosureMenu(window: EndgameWindowSnapshot): boolean {
  return window.type === NHW_MENU
    && window.menuPrompt === ""
    && window.menuItems.some((item) => item.identifier !== null);
}

/**
 * Convert core disclosure questions into concise result-tab labels.
 * @param query - exact question emitted by the current NetHack core.
 * @returns a stable player-facing label, or the original query if unknown.
 */
function disclosureTitle(query: string): string {
  if (INVENTORY_DISCLOSURE_QUERY.test(query)) {
    return "Identified Possessions";
  }
  if (query === "Do you want to see your attributes?") {
    return "Final Attributes";
  }
  if (query === "Do you want an account of creatures vanquished?") {
    return "Vanquished Creatures";
  }
  if (query === "Do you want a list of species genocided?") {
    return "Genocided Species";
  }
  if (query === "Do you want a list of extinct species?") {
    return "Extinct Species";
  }
  if (query === "Do you want a list of species genocided and extinct?") {
    return "Genocided and Extinct Species";
  }
  if (query === "Do you want to see your conduct?") {
    return "Conduct";
  }
  if (query === "Do you want to see your conduct and achievements?") {
    return "Conduct and Achievements";
  }
  if (query === "Do you want to see the dungeon overview?") {
    return "Dungeon Overview";
  }
  return query;
}

/** Copy one styled text line. */
function copyLine(line: TextLine): TextLine {
  return { text: line.text, attribute: line.attribute };
}

/** Copy one menu item and its optional glyph value. */
function copyMenuItem(item: MenuItem): MenuItem {
  return {
    ...item,
    glyph: item.glyph ? { ...item.glyph } : null,
  };
}

/** Freeze one owner token before it outlives its session. */
function freezeOwner(owner: EndgameCollectorOwner): EndgameCollectorOwner {
  return Object.freeze({ ...owner });
}

/** Deep-freeze every nested value retained by a completed summary. */
function freezeSummary(summary: EndgameSummary): EndgameSummary {
  const sections = summary.sections.map((section) => {
    const blocks = section.blocks.map((block) => {
      if (block.kind === "text") {
        const lines = block.lines.map((line) => Object.freeze({ ...line }));
        return Object.freeze({ ...block, lines: Object.freeze(lines) });
      }
      const lines = block.lines.map((line) => Object.freeze({ ...line }));
      const items = block.items.map((item) =>
        Object.freeze({
          ...item,
          glyph: item.glyph ? Object.freeze({ ...item.glyph }) : null,
        }));
      return Object.freeze({
        ...block,
        lines: Object.freeze(lines),
        items: Object.freeze(items),
      });
    });
    return Object.freeze({ ...section, blocks: Object.freeze(blocks) });
  });
  return Object.freeze({
    owner: freezeOwner(summary.owner),
    sections: Object.freeze(sections),
  });
}
