import { createHash } from "node:crypto";
import {
  mkdtemp,
  mkdir,
  readFile,
  readdir,
  rename,
  rm,
  stat,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { PNG } from "pngjs";
import { afterEach, describe, expect, it } from "vitest";
import {
  generateTileAssets,
  verifyTileAssets,
} from "./tile-assets.mjs";
import {
  createTileText,
  solidTileRows,
} from "./__fixtures__/tile-text-fixture.mjs";

const repositoryRoot = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "../../..",
);
const officialSourceDirectory = join(repositoryRoot, "win/share");
const fixtureTilemap = "/* fixture tilemap authority */\n";
const temporaryDirectories = [];

/**
 * Create four small source files and an empty output directory.
 * @returns {Promise<{
 *   root: string,
 *   inputDirectory: string,
 *   outputDirectory: string
 * }>}
 * temporary fixture paths.
 */
async function assetFixture() {
  const root = await mkdtemp(join(tmpdir(), "blisshack-tiles-"));
  const inputDirectory = join(root, "input");
  const outputDirectory = join(root, "output");
  temporaryDirectories.push(root);
  await Promise.all([
    mkdir(inputDirectory),
    mkdir(outputDirectory),
  ]);
  await Promise.all([
    writeFile(
      join(inputDirectory, "monsters.txt"),
      createTileText([{
        index: 0,
        name: "test monster,male",
        rows: solidTileRows("A"),
      }]),
      "utf8",
    ),
    writeFile(
      join(inputDirectory, "objects.txt"),
      createTileText([{
        index: 0,
        name: "test object",
        rows: solidTileRows("B"),
      }]),
      "utf8",
    ),
    writeFile(
      join(inputDirectory, "other.txt"),
      createTileText([
        { index: 0, name: "unexplored", rows: solidTileRows("C") },
        { index: 1, name: "nothing", rows: solidTileRows(".") },
      ]),
      "utf8",
    ),
    writeFile(
      join(inputDirectory, "decals.txt"),
      createTileText([
        { index: 0, name: "decal_delimiter", rows: solidTileRows(".") },
        { index: 1, name: "decal_pet", rows: solidTileRows("A") },
        { index: 2, name: "decal_pile", rows: solidTileRows("B") },
      ]),
      "utf8",
    ),
    writeFile(join(inputDirectory, "tilemap.c"), fixtureTilemap, "utf8"),
  ]);
  return { root, inputDirectory, outputDirectory };
}

/**
 * Read the generated manifest.
 * @param {string} outputDirectory - Generated asset directory.
 * @returns {Promise<Record<string, unknown>>} Parsed manifest.
 */
async function readManifest(outputDirectory) {
  return JSON.parse(
    await readFile(join(outputDirectory, "nethack-classic.json"), "utf8"),
  );
}

/**
 * Capture generated bytes and modification times.
 * @param {string} directory - Asset directory.
 * @returns {Promise<object>} Comparable directory snapshot.
 */
async function assetSnapshot(directory) {
  const names = (await readdir(directory)).sort();
  return Object.fromEntries(await Promise.all(names.map(async (name) => {
    const path = join(directory, name);
    const metadata = await stat(path, { bigint: true });
    return [name, {
      bytes: await readFile(path),
      mtimeNs: metadata.mtimeNs,
    }];
  })));
}

/**
 * Read one atlas pixel from a tile-local coordinate.
 * @param {PNG} png - Decoded atlas.
 * @param {number} tileIndex - Zero-based atlas tile index.
 * @param {number} tileX - Horizontal pixel inside the tile.
 * @param {number} tileY - Vertical pixel inside the tile.
 * @param {number} columns - Atlas column count.
 * @returns {number[]} RGBA values.
 */
function tilePixel(png, tileIndex, tileX, tileY, columns) {
  const x = (tileIndex % columns) * 16 + tileX;
  const y = Math.floor(tileIndex / columns) * 16 + tileY;
  const offset = (y * png.width + x) * 4;
  return [...png.data.subarray(offset, offset + 4)];
}

afterEach(async () => {
  await Promise.all(
    temporaryDirectories.splice(0).map((directory) =>
      rm(directory, { recursive: true, force: true })
    ),
  );
});

describe("tile asset generation", () => {
  it("writes byte-identical PNG and manifest output for identical input", async () => {
    const first = await assetFixture();
    const second = await assetFixture();

    await generateTileAssets({ ...first, columns: 2 });
    await generateTileAssets({ ...second, columns: 2 });

    const [firstPng, secondPng, firstJson, secondJson] = await Promise.all([
      readFile(join(first.outputDirectory, "nethack-classic.png")),
      readFile(join(second.outputDirectory, "nethack-classic.png")),
      readFile(join(first.outputDirectory, "nethack-classic.json")),
      readFile(join(second.outputDirectory, "nethack-classic.json")),
    ]);
    expect(firstPng).toEqual(secondPng);
    expect(firstJson).toEqual(secondJson);

    const manifest = JSON.parse(firstJson.toString("utf8"));
    expect(manifest).toMatchObject({
      formatVersion: 1,
      tile: { width: 16, height: 16 },
      atlas: {
        file: "nethack-classic.png",
        columns: 2,
        rows: 4,
        tileCount: 8,
        sha256: createHash("sha256").update(firstPng).digest("hex"),
      },
      sources: [
        { file: "monsters.txt", tileCount: 1 },
        { file: "objects.txt", tileCount: 1 },
        { file: "other.txt", tileCount: 2 },
        { file: "decals.txt", tileCount: 3 },
      ],
      mappingSource: {
        file: "tilemap.c",
        sha256: createHash("sha256").update(fixtureTilemap).digest("hex"),
      },
      segments: [
        {
          id: "monsters",
          source: "monsters.txt",
          firstTile: 0,
          tileCount: 1,
          transform: "identity",
        },
        {
          id: "objects",
          source: "objects.txt",
          firstTile: 1,
          tileCount: 1,
          transform: "identity",
        },
        {
          id: "other",
          source: "other.txt",
          firstTile: 2,
          tileCount: 2,
          transform: "identity",
        },
        {
          id: "statues",
          source: "monsters.txt",
          firstTile: 4,
          tileCount: 1,
          transform: "grayscale",
        },
        {
          id: "decals",
          source: "decals.txt",
          firstTile: 5,
          tileCount: 3,
          transform: "identity",
        },
      ],
      specialTiles: {
        blank: 3,
        unexplored: 2,
        petMark: 6,
        pileMark: 7,
      },
    });
  });

  it("matches the official source order, counts, checksums, and tilemap layout", async () => {
    const root = await mkdtemp(join(tmpdir(), "blisshack-official-tiles-"));
    const outputDirectory = join(root, "output");
    temporaryDirectories.push(root);
    await mkdir(outputDirectory);

    await generateTileAssets({
      inputDirectory: officialSourceDirectory,
      outputDirectory,
      columns: 40,
    });
    const manifest = await readManifest(outputDirectory);
    const pngBytes = await readFile(
      join(outputDirectory, "nethack-classic.png"),
    );
    const png = PNG.sync.read(pngBytes);

    expect(manifest.sources).toEqual([
      {
        file: "monsters.txt",
        tileCount: 789,
        sha256: "ad05fc41ec59f87c03a5e2112f57637147637e15f08e2936cbe9cdbc051f2f67",
      },
      {
        file: "objects.txt",
        tileCount: 483,
        sha256: "47474ef6bef1bcd654a240e28be671671b74a6067459cf1af74cefbd64f467b4",
      },
      {
        file: "other.txt",
        tileCount: 243,
        sha256: "87f8642529ab6f3f145851cfe937e18194515acef54cafc96182f80cf3d79a1c",
      },
      {
        file: "decals.txt",
        tileCount: 3,
        sha256: "9a8f7ce8fc2373345e7ea5b49adac4b0f45659d7aba4dfdd44c54c806fe4414d",
      },
    ]);
    expect(manifest.mappingSource).toEqual({
      file: "tilemap.c",
      sha256: "2d863e08da72c0a6f41109b20d420eb45db64eb7ad838a0947badf72b8b8b8d4",
    });
    expect(manifest.atlas).toMatchObject({
      columns: 40,
      rows: 58,
      tileCount: 2307,
      sha256: "c85bfd20d4681147be79927db18bf1ada23d7e2ed400373a43773f10e4f414bb",
    });
    expect(manifest.segments).toEqual([
      {
        id: "monsters",
        source: "monsters.txt",
        firstTile: 0,
        tileCount: 789,
        transform: "identity",
      },
      {
        id: "objects",
        source: "objects.txt",
        firstTile: 789,
        tileCount: 483,
        transform: "identity",
      },
      {
        id: "other",
        source: "other.txt",
        firstTile: 1272,
        tileCount: 243,
        transform: "identity",
      },
      {
        id: "statues",
        source: "monsters.txt",
        firstTile: 1515,
        tileCount: 789,
        transform: "grayscale",
      },
      {
        id: "decals",
        source: "decals.txt",
        firstTile: 2304,
        tileCount: 3,
        transform: "identity",
      },
    ]);
    expect(manifest.specialTiles).toMatchObject({
      blank: 1470,
      unexplored: 1469,
      petMark: 2305,
      pileMark: 2306,
    });
    expect([
      tilePixel(png, 0, 7, 7, 40), // giant ant
      tilePixel(png, 789, 3, 1, 40), // strange object
      tilePixel(png, 1272, 0, 0, 40), // stone
      tilePixel(png, 1515, 7, 7, 40), // giant ant statue
      tilePixel(png, 2305, 12, 0, 40), // pet mark
      tilePixel(png, 2306, 2, 0, 40), // pile mark
    ]).toEqual([
      [145, 71, 0, 255],
      [255, 108, 0, 255],
      [108, 145, 182, 255],
      [149, 149, 149, 255],
      [255, 0, 0, 255],
      [255, 255, 255, 255],
    ]);
  });
});

describe("tile asset verification", () => {
  it("accepts current assets without modifying them", async () => {
    const fixture = await assetFixture();
    await generateTileAssets({ ...fixture, columns: 2 });
    const before = await assetSnapshot(fixture.outputDirectory);

    await expect(verifyTileAssets(fixture)).resolves.toMatchObject({
      formatVersion: 1,
    });

    expect(await assetSnapshot(fixture.outputDirectory)).toEqual(before);
  });

  it("recovers an interrupted directory publication before regenerating", async () => {
    const fixture = await assetFixture();
    await generateTileAssets({ ...fixture, columns: 2 });
    const backupDirectory = join(fixture.root, ".output.previous");
    await rename(fixture.outputDirectory, backupDirectory);

    await generateTileAssets({ ...fixture, columns: 2 });

    await expect(verifyTileAssets(fixture)).resolves.toMatchObject({
      formatVersion: 1,
    });
    expect(await readdir(fixture.root)).not.toContain(".output.previous");
  });

  it("restores an interrupted publication before parsing new input", async () => {
    const fixture = await assetFixture();
    await generateTileAssets({ ...fixture, columns: 2 });
    const before = await assetSnapshot(fixture.outputDirectory);
    const backupDirectory = join(fixture.root, ".output.previous");
    await rename(fixture.outputDirectory, backupDirectory);
    await writeFile(
      join(fixture.inputDirectory, "monsters.txt"),
      "# invalid replacement input\n",
    );

    await expect(
      generateTileAssets({ ...fixture, columns: 2 }),
    ).rejects.toThrow();

    expect(await assetSnapshot(fixture.outputDirectory)).toEqual(before);
    expect(await readdir(fixture.root)).not.toContain(".output.previous");
  });

  it("rejects stale source files and corrupted generated files", async () => {
    const stale = await assetFixture();
    await generateTileAssets({ ...stale, columns: 2 });
    const objectPath = join(stale.inputDirectory, "objects.txt");
    const objectText = await readFile(objectPath, "utf8");
    await writeFile(objectPath, objectText.replace("(0, 255, 0)", "(0, 254, 0)"));
    await expect(verifyTileAssets(stale)).rejects.toThrow(
      /objects\.txt.*SHA-256 mismatch/i,
    );

    const staleMapping = await assetFixture();
    await generateTileAssets({ ...staleMapping, columns: 2 });
    await writeFile(
      join(staleMapping.inputDirectory, "tilemap.c"),
      `${fixtureTilemap}/* changed mapping */\n`,
    );
    await expect(verifyTileAssets(staleMapping)).rejects.toThrow(
      /tilemap\.c.*SHA-256 mismatch/i,
    );

    const corruptPng = await assetFixture();
    await generateTileAssets({ ...corruptPng, columns: 2 });
    const pngPath = join(corruptPng.outputDirectory, "nethack-classic.png");
    const png = await readFile(pngPath);
    png[png.length - 1] ^= 0xff;
    await writeFile(pngPath, png);
    await expect(verifyTileAssets(corruptPng)).rejects.toThrow(
      /atlas.*SHA-256 mismatch/i,
    );

    const corruptManifest = await assetFixture();
    await generateTileAssets({ ...corruptManifest, columns: 2 });
    const manifestPath = join(
      corruptManifest.outputDirectory,
      "nethack-classic.json",
    );
    const manifest = await readManifest(corruptManifest.outputDirectory);
    manifest.atlas.tileCount += 1;
    await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
    await expect(verifyTileAssets(corruptManifest)).rejects.toThrow(
      /manifest.*tile count|tile count.*manifest/i,
    );
  });

  it("rejects an atlas whose self-reported checksum was also changed", async () => {
    const fixture = await assetFixture();
    await generateTileAssets({ ...fixture, columns: 2 });
    const pngPath = join(fixture.outputDirectory, "nethack-classic.png");
    const manifestPath = join(
      fixture.outputDirectory,
      "nethack-classic.json",
    );
    const png = PNG.sync.read(await readFile(pngPath));
    png.data[0] ^= 0xff;
    const tamperedBytes = PNG.sync.write(png, {
      bitDepth: 8,
      colorType: 6,
      deflateLevel: 9,
      deflateStrategy: 3,
      inputColorType: 6,
    });
    const manifest = await readManifest(fixture.outputDirectory);
    manifest.atlas.sha256 = createHash("sha256")
      .update(tamperedBytes)
      .digest("hex");
    await Promise.all([
      writeFile(pngPath, tamperedBytes),
      writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`),
    ]);

    await expect(verifyTileAssets(fixture)).rejects.toThrow(
      /canonical|source-generated|does not match/i,
    );
  });
});
